### ISSUE TITLE
Text on Game screen off-center in other locales 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-multiplication#10]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1032, I see the same issue as in https://github.com/phetsims/area-model-algebra/issues/10: With ?stringTest=dynamic it is easy to see that the "Choose Your Level!" text is off-center on the Game screen in locales other than English.

**Visuals**
<img width="1008" alt="Screenshot 2024-01-26 at 1 32 09 PM" src="https://github.com/phetsims/area-model-multiplication/assets/87318828/7b958442-ecee-4736-b9ca-b80e5be4c035">

**Comment by Luisav1** [comment]
Thanks Nancy! The same fix for https://github.com/phetsims/area-model-algebra/issues/10 also fixed this issue as the problem was in `area-model-common`. This was fixed by using an `AlignBox` to center the text when it changes. Below is what it looks like now with `stringTest=dynamic`.
![image](https://github.com/phetsims/area-model-multiplication/assets/52978048/241fd6b2-fe6e-4fa8-8363-8c67ea009aa3)

**Comment by Luisav1** [comment]
This is now fixed more robustly by linking to the `boundsProperty` of the `chooseYourLevelText` and positioning the text in there. This is what it looks like now with `stringTest=dynamic`.
![image](https://github.com/phetsims/area-model-multiplication/assets/52978048/d5dfa05f-f4b2-4523-aab6-dfc513d248a6)

Closing.
