### ISSUE TITLE
Challenge prompt can be off-center

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-multiplication#14]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1042, if the locale is changed while in a level on the game screen, the directive will no longer be centered above the play area. In some locales it is shifted left, while in others it is shifted right. Exiting the level and entering it again fixes the problem.

**Steps to reproduce**
1. Go to the game screen in any locale (ex. Spanish)
2. Select a level
3. Switch locales once in the level (ex. English)

**Visuals**
<img width="541" alt="Screenshot 2024-02-20 at 9 23 40 AM" src="https://github.com/phetsims/area-model-multiplication/assets/87318828/874e95ed-b04e-489e-9c43-4f2253622e98">
<img width="541" alt="Screenshot 2024-02-20 at 9 24 23 AM" src="https://github.com/phetsims/area-model-multiplication/assets/87318828/e97f1c8d-a659-42b3-8505-a518e3c6b3da">

**Comment by Nancy-Salpepi** [comment]
Also seen in https://github.com/phetsims/qa/issues/1041

**Comment by Luisav1** [comment]
Previously, before adding dynamic locale to this sim, the challenge prompt text had its position set whenever the level changed. This is now fixed above since the positioning of the challenge prompt text is linked to whenever that string property changes, meaning either from a change in level or change in locale.

**Comment by KatieWoe** [comment]
This looks ok in rc.2
